"use strict";
const { Router } = require("express");
const { requireAuth } = require("../middleware/auth.middleware");
const controller = require("./ia.controller");
const router = Router();
router.use(requireAuth);
router.post('/recommandations/generer', controller.genererRecommandation);
router.get('/recommandations/derniere', controller.derniereRecommandation);
router.post('/chat', controller.discuter);
router.get('/chat/:conversationId', controller.historiqueConversation);
router.post('/aide-contextuelle', controller.aideContextuelle);
module.exports = router;
