"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.app = void 0;
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const helmet_1 = __importDefault(require("helmet"));
const morgan_1 = __importDefault(require("morgan"));
const auth_routes_1 = __importDefault(require("./auth/auth.routes"));
const profils_routes_1 = __importDefault(require("./profils/profils.routes"));
const offres_routes_1 = __importDefault(require("./offres/offres.routes"));
const candidatures_routes_1 = __importDefault(require("./candidatures/candidatures.routes"));
const filieres_routes_1 = __importDefault(require("./filieres/filieres.routes"));
const admin_routes_1 = __importDefault(require("./admin/admin.routes"));
const ia_routes_1 = __importDefault(require("./ia/ia.routes"));
const error_middleware_1 = require("./middleware/error.middleware");
exports.app = (0, express_1.default)();
exports.app.use((0, helmet_1.default)());
exports.app.use((0, cors_1.default)());
exports.app.use(express_1.default.json());
exports.app.use((0, morgan_1.default)('dev'));
exports.app.get('/health', (_req, res) => res.json({ status: 'ok', service: 'iai-horizon-backend' }));
exports.app.use('/api/auth', auth_routes_1.default);
exports.app.use('/api/profils', profils_routes_1.default);
exports.app.use('/api/offres', offres_routes_1.default);
exports.app.use('/api/candidatures', candidatures_routes_1.default);
exports.app.use('/api/filieres', filieres_routes_1.default);
exports.app.use('/api/admin', admin_routes_1.default);
exports.app.use('/api/ia', ia_routes_1.default);
exports.app.use(error_middleware_1.notFoundMiddleware);
exports.app.use(error_middleware_1.errorMiddleware);
