"use strict";
const { Router } = require("express");
const { requireAuth, requireRole } = require("../middleware/auth.middleware");
const controller = require("./candidatures.controller");
const router = Router();
router.use(requireAuth);
router.post('/', requireRole('etudiant'), controller.postuler);
router.get('/moi', requireRole('etudiant'), controller.mesCandidatures);
router.get('/offre/:offreId', requireRole('entreprise'), controller.candidaturesPourOffre);
router.patch('/:id/accepter', requireRole('entreprise'), controller.accepter);
router.patch('/:id/refuser', requireRole('entreprise'), controller.refuser);
module.exports = router;
