"use strict";
const { Router } = require("express");
const { requireAuth, requireRole } = require("../middleware/auth.middleware");
const controller = require("./admin.controller");
const router = Router();
router.use(requireAuth, requireRole('administrateur'));
router.get('/stats', controller.stats);
router.get('/comptes', controller.comptes);
router.get('/offres', controller.offres);
router.patch('/offres/:id/statut', controller.changerStatutOffre);
router.patch('/entreprises/:id/valider', controller.validerEntreprise);
router.patch('/comptes/:id/bloquer', controller.bloquerCompte);
router.patch('/comptes/:id/debloquer', controller.debloquerCompte);
module.exports = router;